
version: '3.5'
name: wallet-app

services:

## POSTGRES
  postgres-db:
    image: postgres:14
    container_name: wallet-app_db
    environment:
      - POSTGRES_USER=wallet_app_user
      - POSTGRES_PASSWORD=wallet_app_password
      - POSTGRES_DB=wallet-app_db
    ports:
      - "5432:5432"
    networks:
      - wallet-network


  wallet-app:
    container_name: wallet-container
    image: wallet-app
    ports:
    - "8989:8989"
    depends_on:
    - postgres-db
    networks:
      - wallet-network

networks:
  wallet-network:
    driver: bridge




