

name: wallet-app

services:

## POSTGRES
  postgres-db:
    image: postgres:14
    container_name: wallet-app_db
    environment:
      - POSTGRES_USER=wallet_app_user
      - POSTGRES_PASSWORD=wallet_app_password
      - POSTGRES_DB=wallet-app_db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/wallet-data

  java-app:
#    build:
#      context: docker
    image: simple-wallet-api:0.0.1
    container_name: wallet-app-backend
    ports:
      - "8989:8989"
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/wallet-app_db
      SPRING_DATASOURCE_USERNAME: wallet_app_user
      SPRING_DATASOURCE_PASSWORD: wallet_app_password

volumes:
  postgres-data:
